In [1]:
import pandas as pd
import numpy as np
import random

df_exams = pd.read_csv(r"D:\python-for-data-science-main\02.Intro to Pandas\StudentsPerformance.csv")
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [2]:
new_index = np.arange(0, 1000)

In [3]:
random.shuffle(new_index)

In [4]:
df_exams['new_index'] = new_index
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_index
0,female,group B,bachelor's degree,standard,none,72,72,74,543
1,female,group C,some college,standard,completed,69,90,88,456
2,female,group B,master's degree,standard,none,90,95,93,94
3,male,group A,associate's degree,free/reduced,none,47,57,44,448
4,male,group C,some college,standard,none,76,78,75,707
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,244
996,male,group C,high school,free/reduced,none,62,55,55,359
997,female,group C,high school,free/reduced,completed,59,71,65,369
998,female,group D,some college,standard,completed,68,78,77,408
999,female,group D,some college,free/reduced,none,77,86,86,623

In [5]:
df_exams.set_index('new_index', inplace=True)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
543,female,group B,bachelor's degree,standard,none,72,72,74
456,female,group C,some college,standard,completed,69,90,88
94,female,group B,master's degree,standard,none,90,95,93
448,male,group A,associate's degree,free/reduced,none,47,57,44
707,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
244,female,group E,master's degree,standard,completed,88,99,95
359,male,group C,high school,free/reduced,none,62,55,55
369,female,group C,high school,free/reduced,completed,59,71,65
408,female,group D,some college,standard,completed,68,78,77
623,female,group D,some college,free/reduced,none,77,86,86

In [6]:
df_exams.sort_index()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_index
0,female,group B,bachelor's degree,standard,none,72,72,74,543
1,female,group C,some college,standard,completed,69,90,88,456
2,female,group B,master's degree,standard,none,90,95,93,94
3,male,group A,associate's degree,free/reduced,none,47,57,44,448
4,male,group C,some college,standard,none,76,78,75,707
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,244
996,male,group C,high school,free/reduced,none,62,55,55,359
997,female,group C,high school,free/reduced,completed,59,71,65,369
998,female,group D,some college,standard,completed,68,78,77,408
999,female,group D,some college,free/reduced,none,77,86,86,623

In [7]:
df_exams.sort_index(ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_index
999,female,group D,some college,free/reduced,none,77,86,86,623
998,female,group D,some college,standard,completed,68,78,77,408
997,female,group C,high school,free/reduced,completed,59,71,65,369
996,male,group C,high school,free/reduced,none,62,55,55,359
995,female,group E,master's degree,standard,completed,88,99,95,244
...,...,...,...,...,...,...,...,...,...
4,male,group C,some college,standard,none,76,78,75,707
3,male,group A,associate's degree,free/reduced,none,47,57,44,448
2,female,group B,master's degree,standard,none,90,95,93,94
1,female,group C,some college,standard,completed,69,90,88,456
0,female,group B,bachelor's degree,standard,none,72,72,74,543

In [9]:
df_exams.sort_index(ascending=False, inplace=True)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_index
999,female,group D,some college,free/reduced,none,77,86,86,623
998,female,group D,some college,standard,completed,68,78,77,408
997,female,group C,high school,free/reduced,completed,59,71,65,369
996,male,group C,high school,free/reduced,none,62,55,55,359
995,female,group E,master's degree,standard,completed,88,99,95,244
...,...,...,...,...,...,...,...,...,...
4,male,group C,some college,standard,none,76,78,75,707
3,male,group A,associate's degree,free/reduced,none,47,57,44,448
2,female,group B,master's degree,standard,none,90,95,93,94
1,female,group C,some college,standard,completed,69,90,88,456
0,female,group B,bachelor's degree,standard,none,72,72,74,543