In [1]:
import pandas as pd

df_exams = pd.read_csv(r"D:\python-for-data-science-main\02.Intro to Pandas\StudentsPerformance.csv")
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [2]:
df_exams[['gender', 'math score']]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [3]:
type(df_exams[['gender', 'math score']])

pandas.core.frame.DataFrame

In [4]:
df_exams[['gender', 'writing score', 'math score', 'reading score']]

     gender  writing score  math score  reading score
0    female             74          72             72
1    female             88          69             90
2    female             93          90             95
3      male             44          47             57
4      male             75          76             78
..      ...            ...         ...            ...
995  female             95          88             99
996    male             55          62             55
997  female             65          59             71
998  female             77          68             78
999  female             86          77             86

[1000 rows x 4 columns]