In [1]:
import pandas as pd

df_exams = pd.read_csv(r"D:\python-for-data-science-main\02.Intro to Pandas\StudentsPerformance.csv")
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [2]:
df_exams['language score'] = 70
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

In [3]:
import numpy as np
np.arange(0, 1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857,
       858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870,
       871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883,
       884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
       897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909,
       910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
       923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935,
       936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948,
       949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961,
       962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974,
       975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987,
       988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [4]:
len(np.arange(0, 1000))

1000

In [5]:
language_score = np.arange(0, 1000)
len(language_score)

1000

In [6]:
df_exams['language score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [7]:
int_language_score = np.random.randint(1, 100, size=1000)
int_language_score

array([79, 69,  8, 60, 18, 96, 65, 44, 40, 56, 33, 55, 16, 89, 94,  1, 44,
       82, 43, 23, 80, 67, 30,  4, 74, 52, 29, 81, 96, 17, 61, 98, 52,  7,
        5, 10, 12, 89, 33, 79, 17, 60, 32, 84, 63, 88,  1, 63,  2, 87, 43,
       15, 64, 53, 61,  4,  5, 72, 88, 70, 43, 26, 19, 92, 13, 51, 84, 38,
       74, 46, 77, 84, 91, 88, 25, 26, 89, 17, 40,  7, 59, 60, 95,  2, 32,
       56, 55,  8,  9, 14, 31, 96, 35, 20, 29, 41, 50, 31, 17, 60, 82, 29,
       42, 90, 81, 77, 89, 87, 83, 25,  1, 62, 94, 42, 30, 22,  1, 59, 24,
       35, 78, 53, 63, 71, 68, 26, 45, 26, 66, 76, 77, 84, 48, 54, 98, 21,
       81, 93, 56,  4, 88, 85, 46, 63, 33, 66, 59, 12, 34, 62, 43, 55,  6,
       61, 73, 57, 80, 33, 18, 25, 58, 18, 31, 78, 70, 18, 92, 97, 10,  5,
       39, 59, 58,  3, 75, 95, 82, 24, 59,  7, 38, 57, 20,  3, 38, 43,  6,
       79, 10, 57,  2, 57, 40, 21, 22, 14,  1, 79, 12, 65, 83, 69,  1, 46,
        7, 17, 86, 52, 45, 47, 16, 15, 34, 77, 14, 82,  6, 13, 65, 24, 49,
       72, 83, 59, 83, 23, 17, 93, 93, 72, 67, 30, 42, 22, 78, 24,  3, 56,
       50,  4, 77, 74, 59,  9, 88, 18, 96, 21, 44, 79, 64, 57, 29, 95, 17,
       56, 94, 86, 40, 15, 34, 82, 88, 78,  9, 82, 22, 19, 31, 84, 47, 90,
       63, 31,  9, 79, 16, 41, 53, 84, 37, 43, 32,  7, 34, 66, 79, 11, 71,
       17, 97, 71, 85, 21, 90, 73,  6, 68,  7, 93, 72, 19, 99, 36, 23,  9,
       19, 17, 57, 67, 50, 33, 22, 78, 84, 28,  4, 59,  4, 25, 94, 33, 61,
       15, 55, 40, 32, 14, 33, 77, 82, 21, 53, 83, 52, 68, 28, 11, 36,  8,
       38, 24, 56, 97,  4, 96, 79, 48, 82, 14, 98, 73, 96, 95, 93, 13, 64,
        7, 83,  6, 24, 74, 73, 80, 48, 85,  7, 19, 71,  3, 55, 60, 13,  4,
       30, 71, 58, 24, 77, 77, 10, 20, 26,  1, 99, 55, 85,  9, 89, 89, 61,
       62, 28, 35, 67, 42, 50, 24, 95, 91, 89, 79, 48, 54, 32, 95, 31, 29,
       37, 58, 54, 41, 26, 76, 56, 99, 11, 31, 55, 53, 98, 58,  2, 41,  2,
       50,  2, 12, 24, 69, 87, 65, 98, 78, 10, 81, 30, 78, 77, 71, 40, 70,
       11,  8, 33, 21, 35, 63, 33,  9, 38, 94, 24, 66, 65, 35, 23, 52, 94,
       76, 59, 47, 95, 27,  5, 33,  3, 68, 14, 23,  1, 39, 86, 11, 91, 80,
       86, 86, 74, 97, 83,  4,  5, 52, 48, 55, 13, 93, 41, 32,  3, 77, 13,
       39, 26, 40, 93, 56, 68, 80, 87, 27, 92, 95, 16, 25, 24, 72, 87,  9,
       91, 70, 53, 93, 52, 73, 52, 44, 74, 60, 79, 91, 58, 39, 45, 80, 95,
       34, 62, 12, 48, 80, 51, 69, 33, 10, 16, 17, 19, 17, 10, 18,  7, 18,
       80, 85, 92, 97, 46, 82, 23, 37, 82, 99,  3, 54, 40, 41, 68, 55, 35,
       43, 82, 70, 47, 52, 82, 43,  3, 95, 71, 33, 51, 74, 14, 20, 31, 93,
       11, 58, 57,  1, 39, 31, 64, 61, 85, 43, 33, 89, 67, 84, 85, 71, 38,
       13, 88,  4, 74, 64, 13,  9, 50, 10, 37, 20, 67, 42, 92, 27, 66, 27,
       51,  8, 75, 96, 62, 58,  8, 43, 52, 18, 43, 95,  1, 71, 43, 57, 61,
       18, 19, 43, 51, 84, 69, 72, 74, 23, 77, 42, 66, 18, 97, 91, 57, 43,
       37,  3,  4, 20, 42, 98, 34, 81, 59, 71, 25, 58,  2, 54, 83,  7, 95,
       84, 83, 22, 53, 55, 25, 41,  5, 82, 39, 60, 77, 23, 71, 27, 30, 75,
       54, 71, 43, 16,  7, 53, 21, 79, 47, 14, 64, 81, 55, 69, 33, 54,  9,
       38, 63, 84, 27, 31, 60, 56, 36, 47, 37, 73, 35, 73,  3, 15, 87, 57,
       83, 36, 76, 84, 36, 90, 93, 11, 51, 84,  9, 16, 22, 91, 73, 75, 30,
       63,  4, 74, 46, 44,  3,  7,  4, 77, 53, 18, 16, 77, 65, 49, 72, 75,
       97, 16, 43, 21, 90, 72, 36, 99, 69, 21,  4, 47, 25,  4, 13, 74, 42,
       77, 24, 64, 94, 51, 80, 46, 66, 29, 85, 38, 47, 88, 18, 71, 74, 34,
        8, 38, 41, 58, 64, 57, 76, 63, 38, 39, 74, 20, 24, 88, 10, 16,  4,
       27, 64, 63, 14, 14, 51, 50, 44,  8, 58, 81, 42, 80, 11, 86, 65, 29,
       25, 91, 39,  9, 94, 72, 56, 29, 21, 11, 23, 84, 74, 48, 38, 38, 85,
       88, 35,  6, 65, 67, 89, 95,  2, 26,  7, 91, 76, 15, 56, 74, 96, 52,
       38, 12, 52,  7,  9, 88, 51, 54, 10,  2,  6, 70, 26, 10, 84, 78,  3,
       99, 51, 74, 27, 28, 69, 94,  4, 24,  2, 89,  2, 33, 44, 64, 84, 84,
       69,  8, 95, 40, 18, 13, 33, 95, 96, 28, 68, 94, 90, 91, 40, 20, 66,
       38, 34, 25, 97, 13, 62, 18, 48, 58, 69, 96, 11,  4, 27,  7, 33, 36,
       24, 81, 13, 57, 94, 20, 55, 87, 52, 35,  6, 63, 94, 22, 17,  7, 69,
        8,  3, 96, 79, 95, 92, 45, 29, 18, 21, 75, 22, 92,  5, 67, 93, 59,
       59, 71, 45, 23, 72, 60, 15, 91, 11, 50, 53, 25, 17, 11, 13, 20, 60,
       17,  3, 23, 26,  1, 52, 51, 92, 84, 81, 16, 93, 18, 31, 59, 56, 60,
       18, 33, 47,  3, 63, 51,  1, 46, 98, 89, 20, 44, 14, 72])

In [8]:
min(int_language_score)
max(int_language_score)

99

In [11]:
df_exams['language_score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score
0,female,group B,bachelor's degree,standard,none,72,72,74,0,0
1,female,group C,some college,standard,completed,69,90,88,1,1
2,female,group B,master's degree,standard,none,90,95,93,2,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3,3
4,male,group C,some college,standard,none,76,78,75,4,4
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995,995
996,male,group C,high school,free/reduced,none,62,55,55,996,996
997,female,group C,high school,free/reduced,completed,59,71,65,997,997
998,female,group D,some college,standard,completed,68,78,77,998,998
999,female,group D,some college,free/reduced,none,77,86,86,999,999

In [13]:
np.random.uniform(1,100, size=100)

array([52.09683782, 62.21272076, 59.2282949 , 81.42018745, 99.23660787,
       60.7710412 , 43.78812854, 80.17979581, 20.36619809, 75.92824481,
       44.09691424, 72.08649975, 41.49150864, 86.66174881, 79.54340281,
       68.0936153 , 62.60577509, 42.87811435, 55.713673  , 94.36414129,
       86.3846012 , 98.38298467, 57.90808374, 61.28597339, 66.91677461,
       36.40486653, 98.79476977, 80.16254053, 35.97436719, 54.31891908,
       79.7363215 , 29.4798336 ,  7.66253959, 84.03184725, 48.95782894,
       74.22820889, 55.79486829,  5.95756929, 37.06072854, 32.28662175,
       35.08620219, 55.95259149, 83.95798658, 68.99825018, 23.18464335,
       52.33853131,  6.47156933, 74.15609822, 23.84891016, 53.01164851,
       47.90084292, 83.57649979, 56.49845138, 13.77781328, 98.7865487 ,
       57.48733353, 44.77992439, 17.58511471, 93.78586197, 11.1532247 ,
        5.32528969, 38.64793346, 38.86847435, 37.11145777, 46.87148024,
       99.44733761, 75.90445357, 55.04271561,  5.12860891, 93.30143908,
       93.3701158 , 56.02249897, 18.08192847, 99.77170507, 64.04089505,
       80.51891619, 69.51236286, 32.01163762, 70.38475719, 37.79991501,
        6.64816934, 36.4960163 , 79.23002549, 82.00152539,  2.24033647,
       98.22056861, 62.75072509, 34.53908669, 36.51572141, 17.67474915,
       92.32795381, 40.20080973,  9.92106676, 63.15004316, 14.65530419,
       77.36796615,  9.53385751, 38.30885724, 51.80160479, 27.80946575])